/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ImageOptions {
    blur?: number;
    grayscale?: boolean;
    invert?: boolean;
    resize?: string;
    rotate?: number;
    outputFormat?: string;
}

export declare function processImage(inputPath: string, options: ImageOptions): string;
