/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Options for a single `processImage` call. All fields are optional —
 * omitted operations are skipped entirely rather than applied with a
 * default/no-op value. Operations are applied in a fixed order
 * (blur, brighten, grayscale, huerotate, invert, resize, rotate),
 * regardless of the order fields are set in JS.
 */
export interface ImageOptions {
  /** Gaussian blur sigma. Larger values blur more; cost scales with sigma. */
  blur?: number
  /** Brightness delta applied per-pixel. Positive brightens, negative darkens. */
  brighten?: number
  /** If `true`, converts the image to grayscale. */
  grayscale?: boolean
  /** Hue rotation in degrees (0-360, can wrap). */
  huerotate?: number
  /** If `true`, inverts all pixel colors. */
  invert?: boolean
  /** Target size as a `"WIDTHxHEIGHT"` string, e.g. `"512x512"`. */
  resize?: string
  /**
   * Rotation in degrees. Implementations typically only support
   * multiples of 90.
   */
  rotate?: number
  /**
   * Output format identifier (e.g. `"png"`, `"ico"`, `"webp"`). Falls back
   * to the source image's detected format if omitted.
   */
  outputFormat?: string
}

/**
 * Loads an image from `input_path`, applies the requested operations from
 * `options` in sequence, encodes the result in the requested (or original)
 * format, and writes it to a sibling file named `<original_stem>.<ext>` in
 * the current working directory.
 *
 * Returns the filename that was written on success.
 *
 * # Errors
 * Returns a `NapiError` if the file can't be opened/decoded, an operation
 * fails (e.g. invalid resize string), the output format is unsupported, or
 * the encoded result can't be written to disk.
 */
export declare function processImage(inputPath: string, options: ImageOptions): string
